#!/usr/bin/env python3
"""egress.py — 通用出口哨兵引擎（渠道无关）

设计目标：文件/数据离开本机的"出口"必须过秘密扫描。不同聊天工具的发送命令
各不相同，但共性是：某个二进制 + 特定 flag 携带文件路径。

因此把"哪些二进制是出口、哪个 flag 携带文件"做成【声明式配置】，
一条命令即可为所有渠道生成拦截 shim。接入新聊天工具 = 配置加一行。

配置文件：$DSH_HOME/hooks-egress.json（缺省则用内置默认：仅 lark-cli）
{
  "shim_dir": "~/.dsh/hooks/shims",
  "channels": [
    {"name": "lark-cli",        "file_flags": ["--file"],
     "real_path": "auto"},
    {"name": "wechat-send",     "file_flags": ["--attach", "--image"],
     "real_path": "/usr/local/bin/wechat-send"}
  ]
}
"""
import json
import logging
import os
import re
import shutil
from pathlib import Path

log = logging.getLogger("dsh-hooks")

SHIM_TEMPLATE = """#!/bin/bash
# ⚠️ AUTO-GENERATED by `dsh-hooks install-sentinels` — 请勿手改，重新生成会覆盖
# 渠道出口哨兵: {name}
REAL="{real}"
SCANNER={scanner}
FILE_FLAGS=({flags})

has_file=0
prev=""
for a in "$@"; do
  for f in "${{FILE_FLAGS[@]}}"; do
    [ "$a" = "$f" ] && has_file=1
  done
  prev="$a"
done

if [ "$has_file" = "0" ]; then
  exec "$REAL" "$@"
fi

files=()
prev=""
for a in "$@"; do
  for f in "${{FILE_FLAGS[@]}}"; do
    if [ "$prev" = "$f" ] && [ -n "$a" ]; then files+=("$a"); fi
  done
  prev="$a"
done

for f in "${{files[@]}}"; do
  python3 "$SCANNER" --scan-file "$f" 2>/tmp/dshhooks_scan.$$
  rc=$?
  err=$(cat /tmp/dshhooks_scan.$$ 2>/dev/null); rm -f /tmp/dshhooks_scan.$$
  if [ "$rc" = "3" ]; then
    echo "⛔ [出口哨兵·{name}] 发送被拦截：$err" >&2
    echo "   文件 '$f' 含本机凭据明文，禁止通过该渠道外发。" >&2
    exit 3
  elif [ "$rc" != "0" ]; then
    echo "⚠️ [{name}] 文件扫描失败($err)，为安全起见拒绝发送。" >&2
    exit 3
  fi
done

exec "$REAL" "$@"
"""


def dsh_home() -> Path:
    return Path(os.environ.get("DSH_HOME", os.path.expanduser("~/.dsh")))


def egress_config_path() -> Path:
    return dsh_home() / "hooks-egress.json"


def builtin_scanner_path() -> str:
    return str(Path(__file__).resolve().parent / "builtin_hooks"
               / "known_secret_guard.py")


def _find_real(name: str, exclude_dirs: list) -> str:
    """解析真实二进制路径（跳过我们自己的 shim 目录）。找不到返回 None。"""
    for d in os.environ.get("PATH", "").split(":"):
        if any(d.rstrip("/") == e.rstrip("/") for e in exclude_dirs):
            continue
        cand = Path(d) / name
        if cand.exists() and cand != Path(exclude_dirs[0] if False else ""):
            return str(cand)
    which = shutil.which(name)
    return which


def load_channels(path: str = None) -> list:
    """加载渠道配置。用户配置与内置默认合并（按 name 去重，用户优先）。"""
    p = Path(path) if path else egress_config_path()
    user_channels = []
    if p.exists():
        raw = json.loads(p.read_text(encoding="utf-8"))
        user_channels = raw.get("channels", [])
    builtin = [{"name": "lark-cli", "file_flags": ["--file"],
                "real_path": "auto"}]
    merged = {c["name"]: c for c in builtin}
    for c in user_channels:
        merged[c["name"]] = c
    return [c for c in merged.values() if c.get("name")]


def shim_dir_for(config: dict = None) -> Path:
    cfg = config or {}
    return Path(os.path.expanduser(
        cfg.get("shim_dir", "~/.dsh/hooks/shims")))


def generate_shims(path: str = None) -> list:
    """为所有已配置渠道生成/刷新出口哨兵 shim。返回写入的文件路径列表。"""
    scanner = builtin_scanner_path()
    channels = load_channels(path)
    sdir = shim_dir_for()
    sdir.mkdir(parents=True, exist_ok=True)
    written = []

    # 两遍解析：先收集全部 shim 目录，保证找真实路径时跳过所有 shim
    resolved = []
    for ch in channels:
        name = ch["name"]
        real = ch.get("real_path", "auto")
        if real == "auto":
            found = _find_real(name, exclude_dirs=[str(sdir)])
            if not found:
                log.warning("渠道 %s 找不到真实二进制，跳过（仅生成占位）", name)
                found = f"/usr/bin/true   # TODO: 未找到 {name}，请手动指定 real_path"
        else:
            found = os.path.expanduser(str(real))
        resolved.append((ch, found))

    for ch, real in resolved:
        name = ch["name"]
        flags = " ".join(ch.get("file_flags", ["--file"]))
        content = SHIM_TEMPLATE.format(
            name=name, real=real, scanner=json.dumps(scanner),
            flags=flags)
        shim = sdir / name
        shim.write_text(content, encoding="utf-8")
        shim.chmod(0o755)
        written.append(str(shim))
        log.info("出口哨兵已生成: %s → 真实=%s flags=%s", shim, real, flags)
    return written


def channel_name_pattern() -> str:
    """给 secret_file_guard 用：所有渠道名的正则片段（如 'lark-cli|wechat-send'）。"""
    names = [c["name"] for c in load_channels()]
    names += ["curl", "wget", "nc", "ncat", "mail", "mailx",
              "scp", "rsync"]          # 通用外发工具始终包含
    return "|".join(re.escape(n) for n in sorted(set(names)))
